######################################
#### manual configuration example: ###
#Twitter:
#  access_token: XXX-XXX
#  access_token_secret: XXX
#  consumer_key: XXX
#  consumer_secret: XXX
#
#Discord:
#  - IncludeReplyToUser: false
#    IncludeRetweet: false
#    IncludeUserReply: true
#    custom_message: 'A new tweet!'
#    keyword_sets:
#    - - 'League'    # tweet will be posted if tweet contains all 3 words {League of Legends}, no particular order.
#      - 'of'
#      - 'Legends'
#    - - 'Dota 2'    # tweet will be posted if tweet contains 'Dota 2' in this specific order
#    - - 'MOBA'      # tweet will be posted if it contains 'MOBA'
#    twitter_ids:
#    - '123'         # define as many as you want with a dash {-} at the beginning
#    - '456'
#    twitter_handles:
#    - 'discordapp'
#    twitter_lists:
#    - 'https://twitter.com/rokxx/lists/dota-2'
#    webhook_urls:
#    - 'https://discordapp.com/api/webhooks/123456/XXXX-XXXX'
######################################

# configuration through environment variables
Twitter:
  access_token: 1346130518354477057-ADALusR0Xqq1kvWwxgW3zJysjw4eJJ
  access_token_secret: qtUbevhNG93FWAEK6HsrkqCzz9v8FoPtVMwQ5SvOxOX1F
  consumer_key: IpRFT5qtSOPk76Xc0WGLV7elu
  consumer_secret: i3T7xCLk8wB44HHvSSPREAe8dkyV3FOmULTHC9ThBGVzwDQFiG

Discord:
  - IncludeReplyToUser: true
    IncludeRetweet: true
    IncludeUserReply: true
    IncludeAttachment: true
    IncludeQuote: true
    CreateEmbed: true
    twitter_ids: 
    - '1346130518354477057'
    webhook_urls: 
    - 'https://discord.com/api/webhooks/796657428057423872/Tefo7ms2BQNBODIXiJVzqAbp4eGUyAHux8YADkcUZAM71G5xPOnostBJ7PWaavt8XlJS'
  - IncludeReplyToUser: true
    IncludeRetweet: true
    IncludeUserReply: true
    IncludeAttachment: true
    IncludeQuote: true
    CreateEmbed: true
    twitter_ids: 
    - '1189833545478311936' #xdaiotools
    - '1277001161321537536' #whatisfnf
    - '1313855922792398848' #cookvault
    - '1264491925526253568' #mixeraio
    - '1079785380478504960' #grailgateway
    - '1105496046321442817' #The_Shit_Bot
    - '1327461517478936577' #SGNIKECOP1
    - '1331282912994476033' #gotemgroup
    - '1298127398479699975' #KitchenFNF
    - '1298127398479699975' #coppin_fnf
    - '1146930893883346944' #diaoAIO
    webhook_urls: 
    - 'https://discord.com/api/webhooks/799901645357187092/iw66XD8RqLMxCoEkqQBcXvpBLSU4VYGPEkhnPkLXZiYlp2FxeRCek_UVPTNLwGG85iiy'
  - IncludeReplyToUser: true
    IncludeRetweet: true
    IncludeUserReply: true
    IncludeAttachment: true
    IncludeQuote: true
    CreateEmbed: true
    keyword_sets: 
    - - 'entry'
    - - 'restock'
    twitter_ids: 
    - '1348974086320373763'
    webhook_urls: 
    - 'https://discord.com/api/webhooks/796657428057423872/Tefo7ms2BQNBODIXiJVzqAbp4eGUyAHux8YADkcUZAM71G5xPOnostBJ7PWaavt8XlJS'
